export { default as Header } from './Header/index.vue'
export { default as Slide } from './Slide/index.vue'
export { default as NoSlide } from './NoSlide/index.vue'
export { default as FullMain } from './FullMain/index.vue'
export { default as Foot } from './Foot/index.vue'
